# Generated by Django 2.0.1 on 2018-01-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180112_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='muju',
            name='muju_Reason',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_plan_date',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
