# Generated by Django 2.0.1 on 2018-02-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20180211_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju_date1',
            name='Muju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Muju1', verbose_name='模具维修工单'),
        ),
    ]
