# Generated by Django 2.0.1 on 2018-02-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20180211_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju1',
            name='muju_seq',
            field=models.IntegerField(default='.', max_length=10, verbose_name='项次'),
        ),
    ]
