# Generated by Django 2.0.1 on 2018-02-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20180227_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju1',
            name='muju_seq',
            field=models.IntegerField(default='.', verbose_name='项次'),
        ),
    ]
