# Generated by Django 2.0.1 on 2018-02-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20180227_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muju1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='muju_date1',
            name='id',
        ),
        migrations.AlterField(
            model_name='muju1',
            name='muju_wo',
            field=models.CharField(default='.', max_length=50, primary_key=True, serialize=False, verbose_name='模具维修工单'),
        ),
        migrations.AlterField(
            model_name='muju_date1',
            name='Muju',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Muju1'),
        ),
    ]
