# Generated by Django 2.0.1 on 2018-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180302_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazhupc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default='.', max_length=200)),
                ('prod', models.CharField(default='.', max_length=200)),
                ('material', models.CharField(default='.', max_length=200)),
                ('cycle', models.CharField(default='.', max_length=200)),
                ('xueshu', models.CharField(default='.', max_length=200)),
                ('chann', models.CharField(default='.', max_length=200)),
                ('renshu', models.CharField(default='.', max_length=200)),
                ('ddanliang', models.CharField(default='.', max_length=200)),
                ('day', models.CharField(default='.', max_length=200)),
                ('jh_or_cchu', models.CharField(default='.', max_length=200)),
            ],
        ),
    ]
