# Generated by Django 2.0.1 on 2018-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_yazhupc'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazhupc',
            name='baiban1',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='baiban2',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='baiban3',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='baiban4',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='baiban5',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='beizhu',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='jadonglv',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='rengongognshi',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='shebeigongshi',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban1',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban2',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban3',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban4',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban5',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='zhoupai',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
