# Generated by Django 2.0.1 on 2018-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180112_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='muju',
            name='muju_date1',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date10',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date11',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date12',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date13',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date14',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date15',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date16',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date17',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date18',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date19',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date2',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date20',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date21',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date3',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date4',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date5',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date6',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date7',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date8',
            field=models.CharField(default='.', max_length=1000),
        ),
        migrations.AddField(
            model_name='muju',
            name='muju_date9',
            field=models.CharField(default='.', max_length=1000),
        ),
    ]
