# Generated by Django 2.0.1 on 2018-03-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180308_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazhupc',
            name='baiban6',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='baiban7',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='baiban8',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban6',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban7',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='yazhupc',
            name='wanban8',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
