# Generated by Django 2.0.1 on 2018-03-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180308_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mujuv2',
            name='muju_seq',
            field=models.CharField(default='.', max_length=1000, verbose_name='项次'),
        ),
    ]
