# Generated by Django 2.0.1 on 2018-01-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180112_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_date',
            field=models.DateField(verbose_name='AMRT300日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_wo',
            field=models.CharField(default='.', max_length=50, verbose_name='模具维修工单'),
        ),
    ]
