# Generated by Django 2.0.1 on 2018-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180112_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_Reason',
            field=models.CharField(default='.', max_length=1000, verbose_name='报修原因'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date1',
            field=models.CharField(default='.', max_length=1000, verbose_name='拆模计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date10',
            field=models.CharField(default='.', max_length=1000, verbose_name='CNC实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date11',
            field=models.CharField(default='.', max_length=1000, verbose_name='放电计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date12',
            field=models.CharField(default='.', max_length=1000, verbose_name='放电实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date13',
            field=models.CharField(default='.', max_length=1000, verbose_name='抛光计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date14',
            field=models.CharField(default='.', max_length=1000, verbose_name='抛光实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date15',
            field=models.CharField(default='.', max_length=1000, verbose_name='组立计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date16',
            field=models.CharField(default='.', max_length=1000, verbose_name='组立实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date17',
            field=models.CharField(default='.', max_length=1000, verbose_name='其他计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date18',
            field=models.CharField(default='.', max_length=1000, verbose_name='其他实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date19',
            field=models.CharField(default='.', max_length=1000, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date2',
            field=models.CharField(default='.', max_length=1000, verbose_name='拆模实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date20',
            field=models.CharField(default='.', max_length=1000, verbose_name='维修瓶颈工序'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date21',
            field=models.CharField(default='.', max_length=1000, verbose_name='实际完成日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date3',
            field=models.CharField(default='.', max_length=1000, verbose_name='易损与材料制作计划'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date4',
            field=models.CharField(default='.', max_length=1000, verbose_name='易损与材料制作实际'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date5',
            field=models.CharField(default='.', max_length=1000, verbose_name='线割计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date6',
            field=models.CharField(default='.', max_length=1000, verbose_name='线割实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date7',
            field=models.CharField(default='.', max_length=1000, verbose_name='烧焊计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date8',
            field=models.CharField(default='.', max_length=1000, verbose_name='烧焊实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date9',
            field=models.CharField(default='.', max_length=1000, verbose_name='CNC计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_empe',
            field=models.CharField(default='.', max_length=50, verbose_name='维修人员'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_plan_date',
            field=models.CharField(default='.', max_length=100, verbose_name='模具预计完成日'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_seq',
            field=models.CharField(default='.', max_length=10, verbose_name='项次'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_source_code',
            field=models.CharField(default='.', max_length=50, verbose_name='资源编号'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_source_code_name',
            field=models.CharField(default='.', max_length=50, verbose_name='资源名称'),
        ),
    ]
