# Generated by Django 2.0.1 on 2018-03-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180327_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mujuv2',
            name='muju_seq',
            field=models.IntegerField(default='.', verbose_name='项次'),
        ),
    ]
