# Generated by Django 2.0.1 on 2018-01-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180112_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='模具预计完成日'),
        ),
    ]
