# Generated by Django 2.0.1 on 2018-01-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180112_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_Reason',
            field=models.DateField(blank=True, null=True, verbose_name='报修原因'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date1',
            field=models.DateField(blank=True, null=True, verbose_name='拆模计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date10',
            field=models.DateField(blank=True, null=True, verbose_name='CNC实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date11',
            field=models.DateField(blank=True, null=True, verbose_name='放电计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date12',
            field=models.DateField(blank=True, null=True, verbose_name='放电实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date13',
            field=models.DateField(blank=True, null=True, verbose_name='抛光计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date14',
            field=models.DateField(blank=True, null=True, verbose_name='抛光实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date15',
            field=models.DateField(blank=True, null=True, verbose_name='组立计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date16',
            field=models.DateField(blank=True, null=True, verbose_name='组立实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date17',
            field=models.DateField(blank=True, null=True, verbose_name='其他计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date18',
            field=models.DateField(blank=True, null=True, verbose_name='其他实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date19',
            field=models.DateField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date2',
            field=models.DateField(blank=True, null=True, verbose_name='拆模实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date20',
            field=models.DateField(blank=True, null=True, verbose_name='维修瓶颈工序'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date21',
            field=models.DateField(blank=True, null=True, verbose_name='实际完成日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date3',
            field=models.DateField(blank=True, null=True, verbose_name='易损与材料制作计划'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date4',
            field=models.DateField(blank=True, null=True, verbose_name='易损与材料制作实际'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date5',
            field=models.DateField(blank=True, null=True, verbose_name='线割计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date6',
            field=models.DateField(blank=True, null=True, verbose_name='线割实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date7',
            field=models.DateField(blank=True, null=True, verbose_name='烧焊计划日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date8',
            field=models.DateField(blank=True, null=True, verbose_name='烧焊实际日期'),
        ),
        migrations.AlterField(
            model_name='muju',
            name='muju_date9',
            field=models.DateField(blank=True, null=True, verbose_name='CNC计划日期'),
        ),
    ]
