# Generated by Django 2.0.1 on 2018-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180112_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_Reason',
            field=models.DateField(blank=True, null=True, verbose_name='x报修原因'),
        ),
    ]
