# Generated by Django 2.0.1 on 2018-01-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180115_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_date',
            field=models.DateField(verbose_name='AMRT300日期'),
        ),
    ]
