# Generated by Django 2.0.1 on 2018-01-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20180115_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju',
            name='muju_date20',
            field=models.DateField(blank=True, default='.', null=True, verbose_name='维修瓶颈工序'),
        ),
    ]
