# Generated by Django 2.0.1 on 2018-02-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20180209_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju_date1',
            name='muju_date1',
            field=models.DateField(blank=True, null=True, verbose_name='拆模计划日期'),
        ),
    ]
