# Generated by Django 2.0.1 on 2018-02-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20180211_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muju_date1',
            name='muju_date19',
            field=models.CharField(default='.', max_length=1000, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='muju_date1',
            name='muju_date20',
            field=models.CharField(default='.', max_length=50, verbose_name='维修瓶颈工序'),
        ),
    ]
